FROM oven/bun:1-debian
WORKDIR /app

COPY package.json bun.lock* ./
RUN bun install --frozen-lockfile --ignore-scripts

COPY . .
RUN bunx nuxt prepare
RUN bunx prisma generate

EXPOSE 3000
CMD ["bun", "run", "dev"]
